import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'

export default function Home() {
    const router = useRouter();

    const jsonPlans = router.query.plans.split(';');

    const plans = jsonPlans.map(plan => {
        return JSON.parse(plan);
    });


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href={`${process.env.NEXT_PUBLIC_FAVICON}/favicon.ico`} />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Plans
                </h1>

                <table className={styles.table}>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Benefit</th>
                            <th>Ownership</th>
                            <th>Downpayment</th>
                            <th>Monthly</th>
                            <th>Protection</th>
                            <th>Warranty</th>
                            <th>Service</th>
                        </tr>
                    </thead>
                    <tbody>
                        {plans.map(plan => {
                            return (
                                <tr key={plan.id}>
                                    <td>{plan.name}</td>
                                    <td>{plan.benefit}</td>
                                    <td>{plan.ownership}</td>
                                    <td>{plan.downpayment}</td>
                                    <td>{plan.monthly}</td>
                                    <td>{plan.protection ? 'Yes' : 'No'}</td>
                                    <td>{plan.warranty ? 'Yes' : 'No'}</td>
                                    <td>{plan.service ? 'Yes' : 'No'}</td>
                                </tr>
                            )
                        })}
                    </tbody>
                </table>
            </main>
        </div>
    )
}